### ISSUE TITLE
Mac release?

### ISSUE THREAD

**Issue by dscholtus** [SamuelTS/SketchUp-Universal-Importer-Plugin#1]
Hi Samuel,

Sorry to bother. Is there a mac release coming up?
I really like to export STEP files from my program but can’t convert them to skp currently. (Or via irritating workarounds haha)

Sorry if it’s not on the radar but I think it’s incredible you’re doing this for free!

**Comment by SamuelTallet** [comment]
Hi, Mac release is available now.
