### ISSUE TITLE
Can't download plugin from SketchUcation page

### ISSUE THREAD

**Issue by TinnyTimmy** [SamuelTS/SketchUp-Universal-Importer-Plugin#10]
Can't download plugin from sketchucation page
![123](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/assets/121693540/d6ad54b1-2128-4878-926f-68657d9af6dc)
![1234](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/assets/121693540/e723cb87-fd5b-47b3-bf48-1a9fa4bab68e)

**Comment by SamuelTallet** [comment]
Thanks, I forwarded to the SketchUcation Director since it's a global PluginStore issue.

**Comment by SamuelTallet** [comment]
The Universal Importer plugin can once again be downloaded from the SketchUcation PluginStore.

**Comment by TinnyTimmy** [comment]
Thanks a lot
