### ISSUE TITLE
Error: Failed to convert 3MF file (No much details)

### ISSUE THREAD

**Issue by nfalco79** [SamuelTS/SketchUp-Universal-Importer-Plugin#11]
I download a file from Thingiverse: https://www.thingiverse.com/thing:6162681/files
File named Fanduct_anteriore.3mf

I have try to use this plugin to convert 3MF file in a SKP file but it fails with the following error.
![immagine](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/assets/4160180/2ac4e09f-92d7-4f83-bbc8-578307a6640e)

I had try to run the command in a DOS CLI and it works.
![immagine](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/assets/4160180/c959c1cf-bdfa-4298-ae4a-940d796fbb7a)
An obj file has been generated but it is in a format that I can not manage.

**Comment by SamuelTallet** [comment]
Thanks for your detailed report.
The link you provided gives a `404`.

**Comment by nfalco79** [comment]
Link fixed. Maybe thingverse generate a download link valid only of a short time to avoid post their links somewhere else

**Comment by SamuelTallet** [comment]
3MF files downloaded. Thank you.

**Comment by SamuelTallet** [comment]
Investigation done.

Your `assimp` command exits with a non-zero code, indicating a failure, even if an _.obj_ file is generated, that's why my plugin stops.

One can wait for a fix from [Assimp](https://github.com/assimp/assimp) or I can think about a way to force, in my plugin, importing of _.3mf_ files in "degraded" mode...

**Comment by nfalco79** [comment]
I've try to genere from assimp GUI and than import into sketchup but some surfaces was missing.

**Comment by SamuelTallet** [comment]
I can import *Fanduct_anteriore.3mf* with the latest version (1.2.4) of the plugin. Please reopen issue if problem persists.
