### ISSUE TITLE
Error: Failed to load STEP file: IFC: Unrecognized file schema: AUTOMOTIVE_DESIGN

### ISSUE THREAD

**Issue by CarloSpecchio** [SamuelTS/SketchUp-Universal-Importer-Plugin#15]
Hi 
I get this error when I try to import a STEP file in SketchUp
![UniversalImporterError](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/assets/26480894/0527c748-a659-46da-a94b-50d085db4d13)

What is the problem.
Bonjour,
J'ai l'erreur suivante dans SketchUp pour importer un fichier STEP

![UniversalImporterError](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/assets/26480894/ef193520-e0f4-41e2-bbd3-226c0b6dcc49)

**Comment by SamuelTallet** [comment]
Hi Carlo,

This is a known compatibility issue.
Please report then track issue [here](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/issues/9).

--

Bonjour Carlo,

Il s'agit d'un problème de compatibilité connu.
Veuillez signaler puis suivre le problème [ici](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/issues/9).

**Comment by SamuelTallet** [comment]
Hi,

This issue comes from Assimp (the program used by Universal Importer to convert 3D files).
There is no solution for now.

**Comment by SamuelTallet** [comment]
Hello,

Since Universal Importer v1.2.5, it's possible to import STEP automotive designs without issue.
Please download-install latest version and try again.
