### ISSUE TITLE
Error importing a 3MF file in SketchUp with Universal Importer (v1.2.3) 

### ISSUE THREAD

**Issue by CarloSpecchio** [SamuelTS/SketchUp-Universal-Importer-Plugin#16]
![UniversalImportmerMessage](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/assets/26480894/511b444e-a80e-4e04-9f86-bb8c08787343)

Hi
In order to import an *.3mf file with this plug in for sketchUp, i get the above mentioned message. (I posted same issue with *.step file.
Can anyone, please, explain me what, maybe, I am doing wrong ? VC++ is installed. Can it be that my *.step and *.3mf file is not complete or maybe damaged?

Thank you in advance for any help and/or information regarding this issue.
Best wishes
C.S .

**Comment by SamuelTallet** [comment]
Hi Carlo,

This is a known compatibility issue.
Please report then track issue [here](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/issues/11).

Best regards
