### ISSUE TITLE
Error: Failed to load STEP and 3MF file

### ISSUE THREAD

**Issue by CarloSpecchio** [SamuelTS/SketchUp-Universal-Importer-Plugin#17]
![Universal importer - 3MF file](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/assets/26480894/2f25aaad-d2a9-4982-84e2-28ba6cff4d3c)
![Universal importer - STEP file](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/assets/26480894/6826f961-eb61-48c5-8bb4-b297698fb7f8)

Hi,
I get this error when I try to import a STEP or 3MF file with Universal Importer (version 1.2.3)
Is there a way to fix this and if yes, how to do it.
Thank you for every feedback and information

Best wishes 

CS

**Comment by SamuelTallet** [comment]
Hi,

Please give a try with the new version (1.2.4) released a few minutes ago.

**Comment by CarloSpecchio** [comment]
Hi Samuel,
I installed the new version (as you can see on the attached files) but still get errors.
![UniversalImporter 1 2 4-3MF file](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/assets/26480894/b3c9ea0d-e805-46fa-9c06-a37c082d9da1)
![UniversalImporter 1 2 4-STEP file](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin/assets/26480894/45db1f1a-9fb9-4723-9ef5-e0d334215071)
Is this due to the path length where my files are saved or is it another issue? 
I appreciate any help on this as I would like to import some very (for me) useful STEP files.

Thanks in advance for any feedback and help.

Best wishes 
CS

**Comment by CarloSpecchio** [comment]
Hi Samuel,
In order to import the mentioned STEP file I opened it in FreeCAD and exported the file as a COLLADA file (*.dae).
I imported the DAE file with Universal Importer (1.2.4) and this works. 
Thanks in advance for all.
Best wishes
CS

**Comment by SamuelTallet** [comment]
Hi Carlo,

Thank you for your tests and your tip for the STEP format.
I invite you to continue the discussion in dedicated issues: #15 for your STEP file and #18 for your 3MF file.
