### ISSUE TITLE
[STEP format] Failed to load file: Validation failed: A node of the scenegraph is NULL

### ISSUE THREAD

**Issue by Lamphere** [SamuelTS/SketchUp-Universal-Importer-Plugin#2]
have reinstalled SU2020 run as Administrator via Tig recommendations, have reloaded C++ twice.  Same error occurs. 
![2020-10-28 (2)](https://user-images.githubusercontent.com/31733286/97482532-e3b47d00-191b-11eb-9543-27b9438316df.png)
![2020-10-28 (1)](https://user-images.githubusercontent.com/31733286/97482554-ea42f480-191b-11eb-8af1-8dceb7affdb1.png)

**Comment by Lamphere** [comment]
Have also utilized two different SU2020 models

**Comment by SamuelTallet** [comment]
@Lamphere Thanks for your report. Can you please upload the .OBJ model that fails to a file hoster?

**Comment by Lamphere** [comment]
Samuel,  thank you for the response.  First I apologize for my error in the title.  The source file I am attempting to import into SU2020 is .stp  Per your request here is the file.  I am able to successfully open in my fully paid version of Fusion 360.  I have the paid version of SK2020 as well.  Thank you in advance, I believe your plugin will be a great help to all of us who have to work with other non-native SU files!

The zip file I am attempting to upload is 29mb, please advise of how I can get this file to you.  If you like I can create a shared link in Google or Onedrive, please advise of how I provide the link to you and not as a general public link.

Thanks in advance.

**Comment by SamuelTallet** [comment]
@Lamphere I just sent you a PM at [sketchUcation](https://sketchucation.com/forums/index.php).

**Comment by Lamphere** [comment]
SamuelTS.  Thank you for your generous efforts.  Apparently, I don't have PM privileges at sketchucation even though I have been a non-premium member for a number of years....  
I have the shareable Google folder set up with the files.   Advise, sorry this has been so challenging.

**Comment by SamuelTallet** [comment]
@Lamphere You can send me your Google Drive link to my mailbox.

**Comment by Lamphere** [comment]
Thank you done.

**Comment by SamuelTallet** [comment]
I've not received it. Can you send it again?

**Comment by Lamphere** [comment]
ok will send it again.  I sent if from my gmail and also sent you a separate email.

**Comment by SamuelTallet** [comment]
Well received :)

**Comment by SamuelTallet** [comment]
Import of your .STP models fails with this error: **Failed to load file: Validation failed: A node of the scenegraph is NULL**. This is an Assimp* issue. Unfortunately I can't fix it 😞

(*) Assimp is conversion tool used internally by Universal Importer plugin.
