### ISSUE TITLE
Assimp import error on Mac due to file permissions

### ISSUE THREAD

**Issue by jacksprattt1234** [SamuelTS/SketchUp-Universal-Importer-Plugin#3]
When attempting an import on Mac, the following error occurs:

Universal Importer Error: Command failed: /Users/.../Library/Application Support/SketchUp 2018/SketchUp/Plugins/universal_importer/Assimp/Mac/assimp" info "/Users/.../.UniversalImporter/tmp/import.step" > "/Users/.../.UniversalImporter/tmp/assimp.nfo"
/Users/.../Library/Application Support/SketchUp 2018/SketchUp/Plugins/universal_importer/assimp.rb:166:in `get_texture_refs'
Universal Importer Version: 1.1.5

It's an easy fix. Assimp is missing the execute unix access mode(file permission). chmod 755/777/a+x,  etc. corrects the issue.

**Comment by SamuelTallet** [comment]
@jacksprattt1234 Since [v1.1.6](https://github.com/SamuelTS/SketchUp-Universal-Importer-Plugin/releases) of the plugin, this has been fixed. If problem persists: feel free to reopen #3.
