### ISSUE TITLE
Could not find included file 'universal_importer/load.rb'

### ISSUE THREAD

**Issue by leonardocannarella** [SamuelTS/SketchUp-Universal-Importer-Plugin#4]
Hi! I tried to install this Universal Importer Plugin. 
Now everytime I open SketchUp I see this screen:

![image](https://user-images.githubusercontent.com/11887620/152859518-d5875a47-9144-43a8-a40d-640992f10bab.png)

I tried to change some line of code, but nothing. The file "load.rb" is on the path but SketchUp doesn't see it.

Why?

I'll wait for your response.

Thank you very much

**Comment by SamuelTallet** [comment]
Hi! Can you give me more details please? 😉
- Operating system
- SketchUp version
- Plugin version
- Install method (GitHub, SketchUcation)

**Comment by leonardocannarella** [comment]
Yes sure! Windows 11, SketchUp 2020, Plugin Version 1.1.7, GitHub (then I installed this plugin from the menu "Manage Extension").

Thanks

**Comment by SamuelTallet** [comment]
If you downloaded plugin from GitHub Releases page:

1. Open `%APPDATA%\SketchUp\SketchUp 2020\SketchUp\Plugins` folder with Windows File Explorer.
2. Extract `universal_importer.rb` file and `universal_importer` folder in above `Plugins` folder.
3. Restart SketchUp.
4. If error still occurs: follow [these install instructions](https://github.com/SamuelTallet/SketchUp-Universal-Importer-Plugin#how-to-install-this-plugin).

**Comment by leonardocannarella** [comment]
I resolved the problem downloading directly the .rbz file from SketchUcation!

Thanks a lot for your time
