### ISSUE TITLE
Plugin asks too much questions

### ISSUE THREAD

**Issue by Darkloke** [SamuelTS/SketchUp-Universal-Importer-Plugin#5]
Greetings. 

When i import an *.obj model to SketchUp - it asks me two questions: to enter model height (in mm) and to select a texture for material: default material. If i cancel model height, then all models imported hame the same (i assume - default) height/size. If i cancel texture selection, then model is still displayed correctly. So why all this questions? Arent model already have this asked parameters in itself?

I am asking coz if i import this models to 3Ds Max for example, then all models have different/unique height/size and correctly display textures by default (i.e. w/o/ entering any additional parameters).

**Comment by SamuelTallet** [comment]
Indeed, plugin should discover everything by itself. But until I don't masterize completely subject, I need to balance automation and accuracy. Next plugin version will ask less questions by default. In meanwhile, you can track progress and continue discussion in issues #6 and #7.

Regards.
