### ISSUE TITLE
Wrong scale/size

### ISSUE THREAD

**Issue by SamuelTallet** [SamuelTS/SketchUp-Universal-Importer-Plugin#6]
Sometimes imported model is too small, most of time it is too big...

**Comment by Darkloke** [comment]
There are some projects on github about *.obj importing... Could they help in terms of knowledge how it works?

https://github.com/Bly7/OBJ-Loader
https://github.com/srcnalt/obj-importer

**Comment by drowhunter** [comment]
I second this ,  objects i import are 10000 times too big.  I imported an 8mm screw that was about the size of a building

**Comment by Lamcza** [comment]
> I second this , objects i import are 10000 times too big. I imported an 8mm screw that was about the size of a building

yep stl's are huge :X
any way to scale it down fast they are always 10k bigger or this can be a random number :X?

**Comment by SamuelTallet** [comment]
Since version 1.2.6, the Universal Importer plugin allows the user to specify the units of the source model ; which corrects the scale of the imported model if these units have been correctly specified...
This is blind choice but enough progress to justify closing this issue.
